// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.IMU.DataHub.DAL;

#nullable disable

namespace Project.IMU.DataHub.Migrations
{
    [DbContext(typeof(IMUDataHubDBConfig))]
    partial class IMUDataHubDBConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Project.IMU.DataHub.Models.BatchTestData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BatchID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TestItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TestResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TestTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("t_datahub_batch_testdata");
                });

            modelBuilder.Entity("Project.IMU.DataHub.Models.TBatch", b =>
                {
                    b.Property<string>("BatchID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Position1Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position1Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position2Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position2Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position3Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position3Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position4Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position4Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position5Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position5Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position6Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position6Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrayID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BatchID");

                    b.ToTable("t_datahub_batch");
                });

            modelBuilder.Entity("Project.IMU.DataHub.Models.TDeviceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ConnectionEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ConnectionStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("0");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StationNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_datahub_deviceinfo", (string)null);
                });

            modelBuilder.Entity("Project.IMU.DataHub.Models.TTestConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FailFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsServerEditable")
                        .HasColumnType("bit(1)");

                    b.Property<string>("PassFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerIPAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerPort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("t_datahub_testconfig");
                });

            modelBuilder.Entity("Project.IMU.DataHub.Models.TTray", b =>
                {
                    b.Property<string>("TrayID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentBatchID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLoadTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("TrayID");

                    b.ToTable("t_datahub_tray");
                });
#pragma warning restore 612, 618
        }
    }
}
